{"package_name": "java.security.cert", "subclass_list": [], "class_description": "An exception indicating one of a variety of problems encountered when\n validating a certification path. A CertPathValidatorException provides support for wrapping\n exceptions. The getCause method returns the throwable,\n if any, that caused this exception to be thrown. A CertPathValidatorException may also include the\n certification path that was being validated when the exception was thrown,\n the index of the certificate in the certification path that caused the\n exception to be thrown, and the reason that caused the failure. Use the\n getCertPath, getIndex, and\n getReason methods to retrieve this information. Concurrent Access Unless otherwise specified, the methods defined in this class are not\n thread-safe. Multiple threads that need to access a single\n object concurrently should synchronize amongst themselves and\n provide the necessary locking. Multiple threads each manipulating\n separate objects need not synchronize. ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["GeneralSecurityException"], "Methods": [], "class_name": "CertPathValidatorException", "Vars": null}