{"package_name": "java.util.concurrent", "subclass_list": [], "class_description": "Exception thrown when an error or other exception is encountered\n in the course of completing a result or task. ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["RuntimeException"], "Methods": [{"params": [{"param_name": ["message"], "param_type": "String", "param_description": " the detail message"}, {"param_name": ["cause"], "param_type": "Throwable", "param_description": " the cause (which is saved for later retrieval by the\n         Throwable.getCause() method)"}], "class_name": "CompletionException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a CompletionException with the specified detail\n message and cause.\n", "method_declar": ""}, {"params": [{"param_name": ["cause"], "param_type": "Throwable", "param_description": " the cause (which is saved for later retrieval by the\n         Throwable.getCause() method)"}], "class_name": "CompletionException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a CompletionException with the specified cause.\n The detail message is set to (cause == null ? null :\n cause.toString()) (which typically contains the class and\n detail message of cause).\n", "method_declar": ""}], "class_name": "CompletionException", "Vars": null}