{"package_name": "java.lang.reflect", "subclass_list": [], "class_description": "Thrown by a method invocation on a proxy instance if its invocation\n handler's InvocationHandler#invoke method throws a\n checked exception (a Throwable that is not assignable\n to RuntimeException or Error) that\n is not assignable to any of the exception types declared in the\n throws clause of the method that was invoked on the\n proxy instance and dispatched to the invocation handler. An UndeclaredThrowableException instance contains\n the undeclared checked exception that was thrown by the invocation\n handler, and it can be retrieved with the\n getUndeclaredThrowable() method.\n UndeclaredThrowableException extends\n RuntimeException, so it is an unchecked exception\n that wraps a checked exception. As of release 1.4, this exception has been retrofitted to\n conform to the general purpose exception-chaining mechanism.  The\n \"undeclared checked exception that was thrown by the invocation\n handler\" that may be provided at construction time and accessed via\n the getUndeclaredThrowable() method is now known as the\n cause, and may be accessed via the Throwable#getCause() method, as well as the aforementioned \"legacy\n method.\" ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["RuntimeException"], "Methods": [{"params": [{"param_name": ["undeclaredThrowable"], "param_type": "Throwable", "param_description": " the undeclared checked exception\n          that was thrown"}], "class_name": "UndeclaredThrowableException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an UndeclaredThrowableException with the\n specified Throwable.\n", "method_declar": ""}, {"params": [{"param_name": ["undeclaredThrowable"], "param_type": "Throwable", "param_description": " the undeclared checked exception\n          that was thrown"}, {"param_name": ["s"], "param_type": "String", "param_description": " the detail message"}], "class_name": "UndeclaredThrowableException", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an UndeclaredThrowableException with the\n specified Throwable and a detail message.\n", "method_declar": ""}, {"params": [], "class_name": "UndeclaredThrowableException", "is_static": false, "return_value": {"return_name": [], "return_description": ["the cause of this exception."], "return_type": ["Throwable"]}, "method_name": "getCause", "method_description": "Returns the cause of this exception (the Throwable\n instance wrapped in this UndeclaredThrowableException,\n which may be null).\n", "method_declar": ""}, {"params": [], "class_name": "UndeclaredThrowableException", "is_static": false, "return_value": {"return_name": [], "return_description": ["the undeclared checked exception that was thrown"], "return_type": ["Throwable"]}, "method_name": "getUndeclaredThrowable", "method_description": "Returns the Throwable instance wrapped in this\n UndeclaredThrowableException, which may be null.\n\n \nThis method predates the general-purpose exception chaining facility.\n The Throwable#getCause() method is now the preferred means of\n obtaining this information.\n", "method_declar": ""}], "class_name": "UndeclaredThrowableException", "Vars": null}