{"package_name": "java.lang", "subclass_list": [], "class_description": "Signals that an unexpected exception has occurred in a static initializer.\n An ExceptionInInitializerError is thrown to indicate that an\n exception occurred during evaluation of a static initializer or the\n initializer for a static variable. As of release 1.4, this exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The \"saved throwable\n object\" that may be provided at construction time and accessed via\n the getException() method is now known as the cause,\n and may be accessed via the Throwable#getCause() method, as well\n as the aforementioned \"legacy method.\" ", "class_type": "class", "typealias": [], "interface_list": [""], "class_inherit_list": ["LinkageError"], "Methods": [{"params": [], "class_name": "ExceptionInInitializerError", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an ExceptionInInitializerError with\n null as its detail message string and with no saved\n throwable object.\n A detail message is a String that describes this particular exception.\n", "method_declar": ""}, {"params": [{"param_name": ["thrown"], "param_type": "Throwable", "param_description": " The exception thrown"}], "class_name": "ExceptionInInitializerError", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs a new ExceptionInInitializerError class by\n saving a reference to the Throwable object thrown for\n later retrieval by the getException() method. The detail\n message string is set to null.\n", "method_declar": ""}, {"params": [{"param_name": ["s"], "param_type": "String", "param_description": " the detail message"}], "class_name": "ExceptionInInitializerError", "is_static": false, "return_value": {"return_name": "", "return_description": [], "return_type": []}, "method_name": "init", "method_description": "Constructs an ExceptionInInitializerError with the specified detail\n message string.  A detail message is a String that describes this\n particular exception. The detail message string is saved for later\n retrieval by the Throwable#getMessage() method. There is no\n saved throwable object.\n", "method_declar": ""}, {"params": [], "class_name": "ExceptionInInitializerError", "is_static": false, "return_value": {"return_name": [], "return_description": ["the cause of this error or null if the\n          cause is nonexistent or unknown."], "return_type": ["Throwable"]}, "method_name": "getCause", "method_description": "Returns the cause of this error (the exception that occurred\n during a static initialization that caused this error to be created).\n", "method_declar": ""}, {"params": [], "class_name": "ExceptionInInitializerError", "is_static": false, "return_value": {"return_name": [], "return_description": ["the saved throwable object of this\n         ExceptionInInitializerError, or null\n         if this ExceptionInInitializerError has no saved\n         throwable object."], "return_type": ["Throwable"]}, "method_name": "getException", "method_description": "Returns the exception that occurred during a static initialization that\n caused this error to be created.\n\n \nThis method predates the general-purpose exception chaining facility.\n The Throwable#getCause() method is now the preferred means of\n obtaining this information.\n", "method_declar": ""}], "class_name": "ExceptionInInitializerError", "Vars": null}